---
- name: ensure req. packages are installed
  hosts: nodes, control-plane
  become: true
  gather_facts: false
  tasks:
  - name: Example from an Ansible Playbook
    ansible.builtin.ping:
  - ansible.builtin.apt:
      package:
        - jq
      state: present

- name: upgrade first control plane
  hosts: control-plane[0]
  become: true 
  gather_facts: true
  roles:
  - role: upgrade-cp
    action: upgrade-first-cp

- name: patch other cp
  serial: 1
  hosts: control-plane[1:]
  become: true
  gather_facts: true
  roles:
  - role: upgrade-cp
    action: upgrade-other-cp

- name: upgrade packages on control planes
  serial: 1
  hosts: control-plane
  become: true
  gather_facts: true
  tasks:
  - include_role:
      name: common
      tasks_from: upgrade-node

- name: upgrade nodes
  serial: 1
  hosts: nodes
  become: true
  gather_facts: true
  roles:
  - role: upgrade-node
