---
# targeted kubernetes version in major.minor
kubeVersion: "1.30"
# targeted crio version in major.minor
crioVersion: "1.28"
# time until a pod is killed
drainGracePeriod: 30
# time until the drain command times out
drainTimeOut: 120s
# time to wait in seconds inbetween upgrade operations
pauseDelayCordon: 5
pauseDelayUncordon: 5
# repo list to remove in /etc/apt/sources.list.d/
repoList:
  - "repo_vanillastack_cloudical_net.list"
  - "devel:kubic:libcontainers:stable:cri-o:1.28.list"
  - "devel:kubic:libcontainers:stable:cri-o:1.27.list"
  - "devel:kubic:libcontainers:stable.list"
  - "kubernetes.list"
