---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: unhold packages
  block:
    - name: kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: install #equals unhold

    - name: kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: install #equals unhold

    - name: kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: install #equals unhold

    - name: cri-o-runc
      ansible.builtin.dpkg_selections:
        name: cri-o-runc
        selection: install #equals unhold

    - name: cri-o
      ansible.builtin.dpkg_selections:
        name: cri-o
        selection: install #equals unhold

- name: upgrade and install
  ansible.builtin.apt:  
    pkg:
    - cri-o-runc
    - cri-o
    - kubelet={{ kube_version }}
    - kubeadm={{ kube_version }}
    - kubectl={{ kube_version }}

- name: hold packages
  block:
    - name: kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: cri-o-runc
      ansible.builtin.dpkg_selections:
        name: cri-o-runc
        selection: hold

    - name: cri-o
      ansible.builtin.dpkg_selections:
        name: cri-o
        selection: hold
