---
- name: include common
  ansible.legacy.include_role:
    name: common

- name: run plan
  ansible.builtin.include_tasks: "controlplane-plan.yaml"

- name: apply upgrade
  ansible.builtin.shell: "kubeadm upgrade apply {{ hostvars['K8S_TOKEN_HOLDER']['plan_version'] }} -y"
