---
- name: Include common
  ansible.legacy.include_role:
    name: common

- name: Run plan
  ansible.builtin.include_tasks: "controlplane-plan.yaml"

- name: Upgrade node
  ansible.builtin.shell: "kubeadm upgrade node"
