---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Get variables
  ansible.builtin.include_tasks: "get-versions.yaml"

- name: Upgrade and install
  ansible.builtin.apt:
    pkg:
      - jq
      - cri-o-runc
      - cri-o
      - kubelet={{ kube_version }}
      - kubeadm={{ kube_version }}
      - kubectl={{ kube_version }}
    allow_change_held_packages: true
    update_cache: true
    state: latest

- name: Hold packages
  block:
    - name: Kubeadm
      ansible.builtin.dpkg_selections:
        name: kubeadm
        selection: hold

    - name: Kubelet
      ansible.builtin.dpkg_selections:
        name: kubelet
        selection: hold

    - name: Kubectl
      ansible.builtin.dpkg_selections:
        name: kubectl
        selection: hold

    - name: Cri-o-runc
      ansible.builtin.dpkg_selections:
        name: cri-o-runc
        selection: hold

    - name: Cri-o
      ansible.builtin.dpkg_selections:
        name: cri-o
        selection: hold

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
